// angular-testing/src/app/components/to-do-list/to-do-list.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnChanges } from '@angular/core';
import { ToDoList } from 'common/dist/types';
import { ToDoComponent } from '../to-do/to-do.component';

@Component({
  selector: 'app-to-do-list',
  standalone: true,
  imports: [CommonModule, ToDoComponent],
  template: `<section class="todo-list">
    <h2>List of ToDos</h2>
    <ul class="todo-list__items">
      <li *ngFor="let toDo of filteredToDoList">
        <app-to-do [completed]="toDo.completed" [title]="toDo.todo"></app-to-do>
      </li>
    </ul>
  </section>`,
})
export class ToDoListComponent implements OnChanges {
  @Input() public toDoList: ToDoList = [];
  @Input() public searchValue: string = '';

  public filteredToDoList: ToDoList = [];

  ngOnChanges(): void {
    if (this.searchValue) {
      this.filteredToDoList = this.toDoList.filter(({ todo }) =>
        todo.toLowerCase().includes(this.searchValue.toLowerCase())
      );
    } else {
      this.filteredToDoList = this.toDoList;
    }
  }
}

// react-testing/src/App/components/ToDoList/ToDoList.tsx
import { FC, useEffect, useState } from 'react'
import { ToDoList as ToDoListType } from 'common/dist/types'
import { ToDo } from '..'

type ToDoListProps = {
  toDoList: ToDoListType
  searchQuery: string
}

export const ToDoList: FC<ToDoListProps> = ({ searchQuery, toDoList }) => {
  const [filteredToDoList, setFilteredToDoList] =
    useState<ToDoListType>(toDoList)

  useEffect(() => {
    if (searchQuery) {
      const filteredList = toDoList.filter(({ todo }) =>
        todo.toLowerCase().includes(searchQuery.toLowerCase())
      )
      setFilteredToDoList(filteredList)
    } else {
      setFilteredToDoList(toDoList)
    }
  }, [searchQuery, toDoList])

  return (
    <section className="todo-list">
      <h2>List of ToDos</h2>
      <ul className="todo-list__items">
        {filteredToDoList.map((toDo, index) => (
          <li key={index}>
            <ToDo {...toDo} />
          </li>
        ))}
      </ul>
    </section>
  )
}
