// angular-testing/src/app/components/search-bar/search-bar.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-search-bar',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: ` <input
    [ngModel]="searchValue"
    (ngModelChange)="searchValueChange.emit($event)"
    class="search-bar"
    type="search"
    placeholder="Type something to filter tasks..."
  />`,
})
export class SearchBarComponent {
  @Input() public searchValue: string = '';
  @Output() public searchValueChange: EventEmitter<string> =
    new EventEmitter<string>();
}

// react-testing/src/App/components/SearchBar/SearchBar.tsx
import { ChangeEvent, FC } from 'react'

type SearchBarProps = {
  searchValue: string
  onSearchValueChange: (value: string) => void
}

export const SearchBar: FC<SearchBarProps> = ({
  onSearchValueChange,
  searchValue,
}) => {
  const searchValueChange = ({
    target: { value },
  }: ChangeEvent<HTMLInputElement>) => onSearchValueChange(value)

  return (
    <input
      value={searchValue}
      className="search-bar"
      type="search"
      placeholder="Type something to filter tasks..."
      onChange={searchValueChange}
    />
  )
}
