// react-testing/src/App/App.tsx
import { FC, useEffect, useState } from 'react'
import { Header, SearchBar, ToDoList } from './components'
import { ToDoList as ToDoListType } from 'common/dist/types'
import { apiService } from './utils'

export const App: FC = () => {
  const [toDoList, setToDoList] = useState<ToDoListType>([])
  const [searchValue, setSearchValue] = useState<string>('')

  useEffect(() => {
    getToDoList()
  }, [])

  const getToDoList = async () => {
    const { todos } = await apiService.getToDos()
    setToDoList(todos)
  }

  return (
    <>
      <Header />
      <main className="content">
        <SearchBar
          searchValue={searchValue}
          onSearchValueChange={(value) => setSearchValue(value)}
        />
        <ToDoList searchQuery={searchValue} toDoList={toDoList} />
      </main>
    </>
  )
}

// angular-testing/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ToDoList } from 'common/dist/types';
import { Observable, map } from 'rxjs';
import { SearchBarComponent, ToDoListComponent } from './components';
import { HeaderComponent } from './components/header/header.component';
import { ApiService } from './services';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    HeaderComponent,
    SearchBarComponent,
    ToDoListComponent,
  ],
  providers: [ApiService],
  template: `<app-header></app-header>
    <main class="content">
      <app-search-bar [(searchValue)]="searchValue"></app-search-bar>
      <app-to-do-list *ngIf="toDoList$ | async as toDoList"
        [searchValue]="searchValue"
        [toDoList]="toDoList"
      ></app-to-do-list>
    </main>`,
})
export class AppComponent {
  public searchValue: string = '';
  public toDoList$: Observable<ToDoList>;

  constructor(apiService: ApiService) {
    this.toDoList$ = apiService.getToDos().pipe(map(({ todos }) => todos));
  }
}
